### PR TITLE
Updated deprecated API endpoint from /users/self to /users?profile=true

### LINKED ISSUE #255: Remove /users/self and implement a new API Endpoint
### Issue Description

Remove /users/self and implement a new API Endpoint /users?profile=true across all repos.

Reference: https://github.com/Real-Dev-Squad/website-backend/pull/2201

Below is the mentioned list of repos where /users/self is currently being used:
1. - [ ]     https://github.com/Real-Dev-Squad/website-members
2. - [ ]     https://github.com/Real-Dev-Squad/website-www
3. - [ ]     https://github.com/Real-Dev-Squad/website-status
4. - [ ]     https://github.com/Real-Dev-Squad/website-welcome
5. - [ ]     https://github.com/Real-Dev-Squad/mobile-app
6. - [ ]     https://github.com/Real-Dev-Squad/website-crypto
7. - [ ]     https://github.com/Real-Dev-Squad/website-calendar
8. - [ ]     https://github.com/Real-Dev-Squad/tiny-site-frontend
9. - [ ]     https://github.com/Real-Dev-Squad/website-dashboard
10. - [ ]     https://github.com/Real-Dev-Squad/website-goals
11. - [ ]     https://github.com/Real-Dev-Squad/website-tests
12. - [ ]     https://github.com/Real-Dev-Squad/docs
13. - [ ]     https://github.com/Real-Dev-Squad/website-tests-1
14. - [ ]     https://github.com/Real-Dev-Squad/members-site
15. - [ ]     https://github.com/Real-Dev-Squad/website-my
16. - [ ]     https://github.com/Real-Dev-Squad/skill-tree-frontend
17. - [ ]     https://github.com/Real-Dev-Squad/website-api-contracts
18. - [ ]     https://github.com/Real-Dev-Squad/github-vf-project

### Expected Behavior

We should have removed the usage of /users/self API Endpoint and should be using new API endpoint /users?profile=true

### Current Behavior

Currently, we are using the /users/self API Endpoint.

### Reproducibility

 - [x] This issue is reproducible
 - [ ] This issue is not reproducible

### Steps to Reproduce
1. Go to every repo and check where we are using and calling /users/self.

### Severity/Priority
 - [ ] Critical
 - [x] High
 - [ ] Medium
 - [ ] Low

### Checklist

- [x] I have read and followed the project's code of conduct.
- [x] I have searched for similar issues before creating this one.
- [x] I have provided all the necessary information to understand and reproduce the issue.
- [x] I am willing to contribute to the resolution of this issue.

### PR DESCRIPTION
**Pull request by Hariom01010**
Date: 09 Dec 2024

Developer Name: Hariom Vashista

---

## Issue Ticket Number

Fixes: Real-Dev-Squad/todo-action-items#255 repo#12
## Description

This PR aims to change the documentation and update the /users/self API endpoint to /users?profile=true
### Documentation Updated?

- [X] Yes
- [ ] No

### Under Feature Flag

- [ ] Yes
- [X] No

### Database Changes

- [ ] Yes
- [X] No

### Breaking Changes

- [ ] Yes
- [X] No

### Development Tested?

- [ ] Yes
- [X] No

## Screenshots
<details>
<summary>Screenshot 1</summary>

</details>

## Test Coverage
<details>
<summary>Screenshot 1</summary>

</details>

### CODE REVIEW

**Review by prakashchoudhary07 — COMMENTED** [review]
Is there a scope for improving the document?

**Comment by Hariom01010** [comment]
I feel sir, the documentation in it's current state is easy to understand and follow for a beginner like me. So i won't suggest any changes as of now (one of the reasons is also that i am not familiar with the backend projects). So i have updated the API endpoint mentioned in the links. But surely in future, if i find something which would improve this documentation would suggest those changes.

**Comment by prakashchoudhary07** [comment]
> I feel sir, the documentation in it's current state is easy to understand and follow for a beginner like me. So i won't suggest any changes as of now (one of the reasons is also that i am not familiar with the backend projects). So i have updated the API endpoint mentioned in the links. But surely in future, if i find something which would improve this documentation would suggest those changes.

See if you can get in touch with 2-3 people who did then setup and get their feedback on it

**Comment by Hariom01010** [comment]
Sure sir will look into it and update here

**Review by vikasosmium — APPROVED** [review]

**Review by Achintya-Chatterjee — APPROVED** [review]

**Pull request merged**
